### ISSUE TITLE
Integration with Pluto possible?

### ISSUE THREAD

**Issue by juliohm** [j-fu/VTKView.jl#1]
Did you have a chance to test the viewer with Pluto?

**Comment by juliohm** [comment]
ping @j-fu

**Comment by j-fu** [comment]
Oh sorry for answering late...

No, not for vtkview. The other point here is that it depends on C++ vtk which is 2000 files to compile, and I so far only succeded on Linux. While I very much would like to see this surviving, it would need more resources to build something from this which would give a smooth julia experience on all OSes. 
For pluto, there would come the additional problem of integrating the OS window maintained by vtk into the notebook.

But: Thanks to @fonsp there is a way to channel data efficiently into javascript, and so there is now PlutoVista.jl which uses Plotly.js for 1D, and vtk.js, the javascript variant of VTK for 2D and 3D. This is made for Pluto and now has much of the functionality of VTKView  (and mostly skips the time to the first plot...).

There is also a slightly higher level API in GridVisualize.jl which can use PlutoVista, GLMakie, PyPlot, Plots (and VTKView...) as  backends. I think it can be quite easily extended to work with other Mesh structures as well.  May be you have a look at PlutoVista and GridVisualize. They are quite young, but IMHO have reached a reasonable level of functionality.

**Comment by juliohm** [comment]
PlutoVista.jl seems like what I need! 😍 Will take a look right now... Closing the issue.
